[package]
name = "ProjectSandBevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy_egui = "0.38.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[lints.clippy]
pedantic = "deny"
nursery = "deny"